HospitalMS/Models/Doctor.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctor
    {
        public Doctor()
        {
            this.Visits = new HashSet<Visit>();
            this.Patients = new HashSet<Patient>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Office { get; set; }
        public string Email { get; set; }
        public string Telephone { get; set; }
        public string Address { get; set; }
        public int TypeOfDoctorId { get; set; }
    
        public virtual TypeOfDoctor TypeOfDoctor { get; set; }
        public virtual ICollection<Visit> Visits { get; set; }
        public virtual ICollection<Patient> Patients { get; set; }
    }
}

HospitalMS/Models/Metadata/Doctor.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HospitalMS.Models
{
    [MetadataType(typeof(DoctorAttributes))]
    public partial class Doctor
    {
    }

    public partial class DoctorAttributes
    {
        public int Id { get; set; }


        [Required(ErrorMessage = "Enter doctor's Name.")]
        public string Name { get; set; }


        [Required(ErrorMessage = "Enter doctor's Office.")]
        public string Office { get; set; }


        [Required(ErrorMessage = "Enter doctor's Email.")]
        [EmailAddress(ErrorMessage = "Enter a valid Email address.")]
        public string Email { get; set; }


        [Required(ErrorMessage = "Enter doctor's Telephone.")]
        [RegularExpression("[0-9]{3}-[0-9]{3}-[0-9]{4}")]
        public string Telephone { get; set; }


        [Required(ErrorMessage = "Enter doctor's Address.")]
        public string Address { get; set; }


        [Display(Name = "Type of Doctor")]
        public int TypeOfDoctorId { get; set; }


        [Display(Name = "Type of Doctor")]
        public virtual TypeOfDoctor TypeOfDoctor { get; set; }


        public virtual ICollection<Visit> Visits { get; set; }

        public virtual ICollection<Patient> Patients { get; set; }

    }
}

HospitalMS/Controllers/DoctorsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using HospitalMS.Models;

namespace HospitalMS.Controllers
{
    public class DoctorsController : AuthController
    {
        private ContextClass db = new ContextClass();

        // GET: Doctors
        public ActionResult Index()
        {
            return View(db.Doctors.ToList());
        }

        [HttpPost]
        public ActionResult Index(string search)
        {
            return View(db.Doctors.Where(x => search == null || x.Name.Contains(search) || x.TypeOfDoctor.Name.Contains(search)).ToList());
        }

        // GET: Doctors/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Doctor doctor = db.Doctors.Find(id);
            if (doctor == null)
            {
                return HttpNotFound();
            }
            return View(doctor);
        }

        // GET: Doctors/Create
        public ActionResult Create()
        {
            ViewBag.TypeOfDoctorId = new SelectList(db.TypeOfDoctors, "Id", "Name");
            return View();
        }

        // POST: Doctors/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Office,Email,Telephone,Address,TypeOfDoctorId")] Doctor doctor)
        {
            if (ModelState.IsValid)
            {
                db.Doctors.Add(doctor);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.TypeOfDoctorId = new SelectList(db.TypeOfDoctors, "Id", "Name", doctor.TypeOfDoctorId);
            return View(doctor);
        }

        // GET: Doctors/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Doctor doctor = db.Doctors.Find(id);
            if (doctor == null)
            {
                return HttpNotFound();
            }
            ViewBag.TypeOfDoctorId = new SelectList(db.TypeOfDoctors, "Id", "Name", doctor.TypeOfDoctorId);
            return View(doctor);
        }

        // POST: Doctors/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Office,Email,Telephone,Address,TypeOfDoctorId")] Doctor doctor)
        {
            if (ModelState.IsValid)
            {
                db.Entry(doctor).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.TypeOfDoctorId = new SelectList(db.TypeOfDoctors, "Id", "Name", doctor.TypeOfDoctorId);
            return View(doctor);
        }

        // GET: Doctors/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Doctor doctor = db.Doctors.Find(id);
            if (doctor == null)
            {
                return HttpNotFound();
            }
            return View(doctor);
        }

        // POST: Doctors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Doctor doctor = db.Doctors.Find(id);
            db.Doctors.Remove(doctor);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult Home()
        {
            return RedirectToAction("Index", "Home");
        }

        public ActionResult Doctors()
        {
            return RedirectToAction("Index");
        }

        public ActionResult Patients()
        {
            return RedirectToAction("Index", "Patients");
        }

        public ActionResult Visits()
        {
            return RedirectToAction("Index", "Visits");
        }
    }
}

HospitalMS/Controllers/TypeOfDoctorsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using HospitalMS.Models;

namespace HospitalMS.Controllers
{
    public class TypeOfDoctorsController : AuthController
    {
        private ContextClass db = new ContextClass();

        // GET: TypeOfDoctors
        public ActionResult Index()
        {
            return View(db.TypeOfDoctors.ToList());
        }

        [HttpPost]
        public ActionResult Index(string search)
        {
            return View(db.TypeOfDoctors.Where(x => search == null || x.Name.Contains(search) || x.Description.Contains(search)).ToList());
        }

        // GET: TypeOfDoctors/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TypeOfDoctor typeOfDoctor = db.TypeOfDoctors.Find(id);
            if (typeOfDoctor == null)
            {
                return HttpNotFound();
            }
            return View(typeOfDoctor);
        }

        // GET: TypeOfDoctors/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: TypeOfDoctors/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Description")] TypeOfDoctor typeOfDoctor)
        {
            if (ModelState.IsValid)
            {
                db.TypeOfDoctors.Add(typeOfDoctor);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(typeOfDoctor);
        }

        // GET: TypeOfDoctors/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TypeOfDoctor typeOfDoctor = db.TypeOfDoctors.Find(id);
            if (typeOfDoctor == null)
            {
                return HttpNotFound();
            }
            return View(typeOfDoctor);
        }

        // POST: TypeOfDoctors/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Description")] TypeOfDoctor typeOfDoctor)
        {
            if (ModelState.IsValid)
            {
                db.Entry(typeOfDoctor).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(typeOfDoctor);
        }

        // GET: TypeOfDoctors/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TypeOfDoctor typeOfDoctor = db.TypeOfDoctors.Find(id);
            if (typeOfDoctor == null)
            {
                return HttpNotFound();
            }
            return View(typeOfDoctor);
        }

        // POST: TypeOfDoctors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            TypeOfDoctor typeOfDoctor = db.TypeOfDoctors.Find(id);
            db.TypeOfDoctors.Remove(typeOfDoctor);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

HospitalMS/Views/Doctors/Create.cshtml
@model HospitalMS.Models.Doctor

@{
    ViewBag.Title = "Create Page";
}

<h2>Create</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Doctor</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Office, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Office, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Office, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Telephone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Telephone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Telephone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.TypeOfDoctorId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TypeOfDoctorId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TypeOfDoctorId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

HospitalMS/Views/Doctors/Delete.cshtml
@model HospitalMS.Models.Doctor

@{
    ViewBag.Title = "Delete Page";
}

<h2>Delete</h2>

<div>
    <h4>Doctor</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Office)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Office)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Telephone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Telephone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TypeOfDoctor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TypeOfDoctor.Name)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            @Html.ActionLink("Back to List", "Index") |
            <input type="submit" value="Delete" class="btn btn-default" onclick="return confirm('Are you sure you want to delete this?');" />
        </div>
    }
</div>

HospitalMS/Views/Doctors/Details.cshtml
@model HospitalMS.Models.Doctor

@{
    ViewBag.Title = "Details Page";
}

<h2>Details</h2>

<div>
    <h4>Doctor</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Office)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Office)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Telephone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Telephone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TypeOfDoctor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TypeOfDoctor.Name)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

HospitalMS/Views/Doctors/Edit.cshtml
@model HospitalMS.Models.Doctor

@{
    ViewBag.Title = "Edit Page";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Doctor</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Office, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Office, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Office, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Telephone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Telephone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Telephone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TypeOfDoctorId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TypeOfDoctorId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TypeOfDoctorId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

HospitalMS/Views/Doctors/Index.cshtml
@model IEnumerable<HospitalMS.Models.Doctor>

@{
    ViewBag.Title = "Doctors Page";
}

<h2>Doctors</h2>

<div style="float: left">
    @Html.ActionLink("Create New", "Create") |
    @Html.ActionLink("View All", "Index")
</div>

<div style="float: right">
    @using (Html.BeginForm("Index", "Doctors", FormMethod.Post))
    {
        @Html.Label("search", "Search by")<span>&nbsp;</span>
        @Html.TextBox("search", "", new { placeholder = "Name or Type of Doctor" })
        <input type="submit" value="Search" />
    }
</div>
<div>&nbsp;</div>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Office)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Telephone)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Address)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TypeOfDoctor)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.ActionLink(item.Name, "Details", "Doctors", new { id = item.Id }, null)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Office)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Telephone)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address)
            </td>
            <td>
                @Html.ActionLink(item.TypeOfDoctor.Name, "Details", "TypeOfDoctors", new { id = item.TypeOfDoctor.Id }, null)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
    }

    @if (Model.Count() == 0)
    {
        <tr>
            <td colspan="7">No Doctors found.</td>
        </tr>
    }

</table>