HospitalMS/Models/Metadata/Visit.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace HospitalMS.Models
{
    [MetadataType(typeof(VisitAttributes))]
    public partial class Visit
    {
    }

    public partial class VisitAttributes
    {
        public int Id { get; set; }


        [Display(Name = "Date of Visit")]
        [Required(ErrorMessage = "Choose Date of Visit.")]
        public System.DateTime DateOfVisit { get; set; }


        public string Complaint { get; set; }


        [Display(Name = "Doctor")]
        public int DoctorId { get; set; }


        [Display(Name = "Patient")]
        public int PatientId { get; set; }


        [Display(Name = "Attending Doctor")]
        public virtual Doctor Doctor { get; set; }


        [Display(Name = "Patient")]
        public virtual Patient Patient { get; set; }
    }
}

HospitalMS/Models/Visit.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visit
    {
        public int Id { get; set; }
        public System.DateTime DateOfVisit { get; set; }
        public string Complaint { get; set; }
        public int DoctorId { get; set; }
        public int PatientId { get; set; }
    
        public virtual Doctor Doctor { get; set; }
        public virtual Patient Patient { get; set; }
    }
}

HospitalMS/Controllers/VisitsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using HospitalMS.Models;

namespace HospitalMS.Controllers
{
    public class VisitsController : AuthController
    {
        private ContextClass db = new ContextClass();

        // GET: Visits
        public ActionResult Index()
        {
            var visits = db.Visits.Include(v => v.Doctor).Include(v => v.Patient);
            return View(visits.ToList());
        }

        [HttpPost]
        public ActionResult Index(string search)
        {
            return View(db.Visits.Where(x => search == null || x.Patient.Name.Contains(search) || x.Doctor.Name.Contains(search)).ToList());
        }

        // GET: Visits/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Visit visit = db.Visits.Find(id);
            if (visit == null)
            {
                return HttpNotFound();
            }
            return View(visit);
        }

        // GET: Visits/Create
        public ActionResult Create()
        {
            ViewBag.DoctorId = new SelectList(db.Doctors, "Id", "Name");
            ViewBag.PatientId = new SelectList(db.Patients, "Id", "Name");
            return View();
        }

        // POST: Visits/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,DateOfVisit,Complaint,DoctorId,PatientId")] Visit visit)
        {
            if (ModelState.IsValid)
            {
                db.Visits.Add(visit);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.DoctorId = new SelectList(db.Doctors, "Id", "Name", visit.DoctorId);
            ViewBag.PatientId = new SelectList(db.Patients, "Id", "Name", visit.PatientId);
            return View(visit);
        }

        // GET: Visits/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Visit visit = db.Visits.Find(id);
            if (visit == null)
            {
                return HttpNotFound();
            }
            ViewBag.DoctorId = new SelectList(db.Doctors, "Id", "Name", visit.DoctorId);
            ViewBag.PatientId = new SelectList(db.Patients, "Id", "Name", visit.PatientId);
            return View(visit);
        }

        // POST: Visits/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,DateOfVisit,Complaint,DoctorId,PatientId")] Visit visit)
        {
            if (ModelState.IsValid)
            {
                db.Entry(visit).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.DoctorId = new SelectList(db.Doctors, "Id", "Name", visit.DoctorId);
            ViewBag.PatientId = new SelectList(db.Patients, "Id", "Name", visit.PatientId);
            return View(visit);
        }

        // GET: Visits/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Visit visit = db.Visits.Find(id);
            if (visit == null)
            {
                return HttpNotFound();
            }
            return View(visit);
        }

        // POST: Visits/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Visit visit = db.Visits.Find(id);
            db.Visits.Remove(visit);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult Home()
        {
            return RedirectToAction("Index", "Home");
        }

        public ActionResult Doctors()
        {
            return RedirectToAction("Index", "Doctors");
        }

        public ActionResult Patients()
        {
            return RedirectToAction("Index", "Patients");
        }

        public ActionResult Visits()
        {
            return RedirectToAction("Index");
        }
    }
}

HospitalMS/Views/Visits/Create.cshtml
@model HospitalMS.Models.Visit

@{
    ViewBag.Title = "Create Page";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Visit</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.DateOfVisit, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @*DateTime format in textbox will not be set since it will depend on the locale used by browser*@
            @Html.EditorFor(model => model.DateOfVisit, new { htmlAttributes = new { @class = "form-control", @type = "datetime-local" } })
            @Html.ValidationMessageFor(model => model.DateOfVisit, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.PatientId, "Patient", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("PatientId", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.PatientId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Complaint, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Complaint, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Complaint, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.DoctorId, "Attending Doctor", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("DoctorId", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.DoctorId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

HospitalMS/Views/Visits/Delete.cshtml
@model HospitalMS.Models.Visit

@{
    ViewBag.Title = "Delete Page";
}

<h2>Delete</h2>

<div>
    <h4>Visit</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.DateOfVisit)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateOfVisit)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Complaint)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Complaint)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Doctor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Doctor.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Patient)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Patient.Name)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            @Html.ActionLink("Back to List", "Index") |
            <input type="submit" value="Delete" class="btn btn-default" onclick="return confirm('Are you sure you want to delete this?');" />
        </div>
    }
</div>

HospitalMS/Views/Visits/Details.cshtml
@model HospitalMS.Models.Visit

@{
    ViewBag.Title = "Details Page";
}

<h2>Details</h2>

<div>
    <h4>Visit</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.DateOfVisit)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateOfVisit)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Complaint)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Complaint)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Doctor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Doctor.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Patient)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Patient.Name)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

HospitalMS/Views/Visits/Edit.cshtml
@model HospitalMS.Models.Visit

@{
    ViewBag.Title = "Edit Page";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Visit</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.DateOfVisit, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateOfVisit, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateOfVisit, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Complaint, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Complaint, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Complaint, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DoctorId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("DoctorId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.DoctorId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PatientId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("PatientId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.PatientId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

HospitalMS/Views/Visits/Index.cshtml
@model IEnumerable<HospitalMS.Models.Visit>

@{
    ViewBag.Title = "Visits Page";
}

<h2>Visits</h2>

<div style="float: left">
    @Html.ActionLink("Create New", "Create") |
    @Html.ActionLink("View All", "Index")
</div>

<div style="float: right">
    @using (Html.BeginForm("Index", "Visits", FormMethod.Post))
    {
        @Html.Label("search", "Search by")<span>&nbsp;</span>
        @Html.TextBox("search", "", new { placeholder = "Patient or Doctor" })
        <input type="submit" value="Search" />
    }
</div>
<div>&nbsp;</div>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.DateOfVisit)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Patient)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Complaint)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Doctor)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Doctor.TypeOfDoctor)
        </th>

        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.DateOfVisit)
            </td>
            <td>
                @Html.ActionLink(item.Patient.Name, "Details", "Patients", new { id = item.PatientId }, null)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Complaint)
            </td>
            <td>
                @Html.ActionLink(item.Doctor.Name, "Details", "Doctors", new { id = item.DoctorId }, null)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Doctor.TypeOfDoctor.Name)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
    }

    @if (Model.Count() == 0)
    {
        <tr>
            <td colspan="5">No Visit History found.</td>
        </tr>
    }

</table>